// flow-typed signature: 4461189e49d8546d9bc31a4a589a4606
// flow-typed version: <<STUB>>/constelation-Button_v^5.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'constelation-Button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'constelation-Button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'constelation-Button/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'constelation-Button/dist/index.js' {
  declare module.exports: $Exports<'constelation-Button/dist/index'>;
}
declare module 'constelation-Button/index' {
  declare module.exports: $Exports<'constelation-Button'>;
}
declare module 'constelation-Button/index.js' {
  declare module.exports: $Exports<'constelation-Button'>;
}
