// flow-typed signature: 4fe2260eb36496c32d3b57e756bf5a5b
// flow-typed version: <<STUB>>/constelation-BackgroundImage_v^5.1.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'constelation-BackgroundImage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'constelation-BackgroundImage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'constelation-BackgroundImage/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'constelation-BackgroundImage/dist/index.js' {
  declare module.exports: $Exports<'constelation-BackgroundImage/dist/index'>;
}
declare module 'constelation-BackgroundImage/index' {
  declare module.exports: $Exports<'constelation-BackgroundImage'>;
}
declare module 'constelation-BackgroundImage/index.js' {
  declare module.exports: $Exports<'constelation-BackgroundImage'>;
}
