// flow-typed signature: dfc2344a73d3b1501b07f9d18d9a1b08
// flow-typed version: <<STUB>>/eslint-plugin-auto-import_v^0.0.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-auto-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-auto-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-auto-import/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-auto-import/lib/rules/auto-const' {
  declare module.exports: any;
}

declare module 'eslint-plugin-auto-import/lib/rules/auto-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-auto-import/tests/lib/rules/auto-const' {
  declare module.exports: any;
}

declare module 'eslint-plugin-auto-import/tests/lib/rules/auto-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-auto-import/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-auto-import/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-auto-import/lib/index'>;
}
declare module 'eslint-plugin-auto-import/lib/rules/auto-const.js' {
  declare module.exports: $Exports<'eslint-plugin-auto-import/lib/rules/auto-const'>;
}
declare module 'eslint-plugin-auto-import/lib/rules/auto-import.js' {
  declare module.exports: $Exports<'eslint-plugin-auto-import/lib/rules/auto-import'>;
}
declare module 'eslint-plugin-auto-import/tests/lib/rules/auto-const.js' {
  declare module.exports: $Exports<'eslint-plugin-auto-import/tests/lib/rules/auto-const'>;
}
declare module 'eslint-plugin-auto-import/tests/lib/rules/auto-import.js' {
  declare module.exports: $Exports<'eslint-plugin-auto-import/tests/lib/rules/auto-import'>;
}
declare module 'eslint-plugin-auto-import/tests/test.js' {
  declare module.exports: $Exports<'eslint-plugin-auto-import/tests/test'>;
}
