// flow-typed signature: fbf15598b5efdc2ed50fff1ccba8ed32
// flow-typed version: <<STUB>>/eslint-config-constelation_v^1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-constelation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-constelation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-constelation/index' {
  declare module.exports: $Exports<'eslint-config-constelation'>;
}
declare module 'eslint-config-constelation/index.js' {
  declare module.exports: $Exports<'eslint-config-constelation'>;
}
