// flow-typed signature: 7bab6ff4aef82c7974a5cfd330f177d8
// flow-typed version: <<STUB>>/serve_v^2.1.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'serve' {
  declare module.exports: any;
}
